// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/nijave/otel-agent-trace-connector/connector/codingagentconnector")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/nijave/otel-agent-trace-connector/connector/codingagentconnector")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                     metric.Meter
	mu                        sync.Mutex
	registrations             []metric.Registration
	CodingAgentActiveTurns    metric.Int64ObservableGauge
	CodingAgentEventsDropped  metric.Int64Counter
	CodingAgentTurnsEmitted   metric.Int64Counter
	CodingAgentTurnsTruncated metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterCodingAgentActiveTurnsCallback sets callback for observable CodingAgentActiveTurns metric.
func (builder *TelemetryBuilder) RegisterCodingAgentActiveTurnsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.CodingAgentActiveTurns, obs: o})
		return nil
	}, builder.CodingAgentActiveTurns)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.CodingAgentActiveTurns, err = builder.meter.Int64ObservableGauge(
		"otelcol_coding_agent_active_turns",
		metric.WithDescription("Codex turns currently held in correlation state. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.CodingAgentEventsDropped, err = builder.meter.Int64Counter(
		"otelcol_coding_agent_events_dropped",
		metric.WithDescription("Redelivered Codex events dropped by within-turn deduplication. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.CodingAgentTurnsEmitted, err = builder.meter.Int64Counter(
		"otelcol_coding_agent_turns_emitted",
		metric.WithDescription("Reconstructed coding-agent turns emitted downstream, labeled by finish reason. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.CodingAgentTurnsTruncated, err = builder.meter.Int64Counter(
		"otelcol_coding_agent_turns_truncated",
		metric.WithDescription("Emitted turns that exceeded max_events_per_turn and dropped events. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
