// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the connector/coding_agent component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("coding_agent")
	ScopeName = "github.com/nijave/otel-agent-trace-connector/connector/codingagentconnector"
)

const (
	LogsToTracesStability   = component.StabilityLevelDevelopment
	TracesToTracesStability = component.StabilityLevelDevelopment
)
